### ISSUE TITLE
Wildfly 10 - Error when login-module-stack-ref specified for auth-module

### ISSUE THREAD

**Issue by Knooger** [imixs/imixs-jwt#6]
When attribute "login-module-stack-ref" is used for element "auth-module" a constructor with String parameter is required in ServerAuthModule impl. (JWTAuthModule) by [JBossServerAuthConfig](https://github.com/picketbox/picketbox/blob/master/security-jboss-sx/jbosssx/src/main/java/org/jboss/security/auth/message/config/JBossServerAuthConfig.java) method at line 249.

Not a big deal, but it took me some time to find out why I was getting error like you described [here](https://developer.jboss.org/thread/275462)

**Comment by rsoika** [comment]
Thanks a lot for that finding! This is really interesting.
So I just added this additional constructor without any action. 
I still did not understand what the login-module-stack  configuration in Wildfly 10 is good for....

Thanks for your help :-)

**Comment by rsoika** [comment]
Missing default constructor makes it impossible to use the module. So we need to add the default constructor too.This is important to get the module working correctly.
